// <auto-generated />
using Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.Address", b =>
=======
            modelBuilder.Entity("Domain.Models.Address", b =>
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("CustId")
                        .HasColumnType("int")
                        .HasColumnName("cust_id");

                    b.HasKey("AddressId")
                        .HasName("PK__address__CAA247C853D7D107");

                    b.HasIndex("CustId");

                    b.ToTable("address", (string)null);
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.Category", b =>
=======
            modelBuilder.Entity("Domain.Models.Category", b =>
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId")
                        .HasName("PK__category__D54EE9B47021D588");

                    b.ToTable("category", (string)null);
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.Delivery", b =>
=======
            modelBuilder.Entity("Domain.Models.Delivery", b =>
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("delivery_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryId"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int")
                        .HasColumnName("agent_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("DeliveryId")
                        .HasName("PK__delivery__1C5CF4F5BC3FDD18");

                    b.HasIndex("AgentId");

                    b.HasIndex("OrderId");

                    b.ToTable("delivery", (string)null);
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.DeliveryAgent", b =>
=======
            modelBuilder.Entity("Domain.Models.DeliveryAgent", b =>
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                {
                    b.Property<int>("AgentId")
                        .HasColumnType("int")
                        .HasColumnName("agent_id");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("AgentId")
                        .HasName("PK__delivery__2C05379EF16E6169");

                    b.ToTable("delivery_agent", (string)null);
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.FoodItem", b =>
=======
            modelBuilder.Entity("Domain.Models.FoodItem", b =>
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("item_name");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keywords");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(2, 1)")
                        .HasColumnName("rating");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int")
                        .HasColumnName("restaurant_id");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("ItemId")
                        .HasName("PK__food_ite__52020FDD44ECF4CD");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("food_items", (string)null);
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.Order", b =>
=======
            modelBuilder.Entity("Domain.Models.Order", b =>
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int")
                        .HasColumnName("restaurant_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("OrderId")
                        .HasName("PK__orders__46596229241C82EF");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("orders", (string)null);
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.OrderItem", b =>
=======
            modelBuilder.Entity("Domain.Models.OrderItem", b =>
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("order_items", (string)null);
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.Restaurant", b =>
=======
            modelBuilder.Entity("Domain.Models.Restaurant", b =>
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                {
                    b.Property<int>("RestaurantId")
                        .HasColumnType("int")
                        .HasColumnName("restaurant_id");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("RestaurantId")
                        .HasName("PK__restaura__3B0FAA91A6DFDE71");

                    b.ToTable("restaurant", (string)null);
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.Review", b =>
=======
            modelBuilder.Entity("Domain.Models.Review", b =>
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int")
                        .HasColumnName("restaurant_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ReviewId")
                        .HasName("PK__review__60883D90252E84FF");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("review", (string)null);
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.User", b =>
=======
            modelBuilder.Entity("Domain.Models.User", b =>
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsValid")
                        .HasMaxLength(255)
                        .HasColumnType("bit")
                        .HasColumnName("is_valid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phoneno")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phoneno");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("PK__users__3213E83F9CBDC252");

                    b.ToTable("users", (string)null);
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.Address", b =>
                {
                    b.HasOne("FoodDeliveryProject.Models.User", "Cust")
=======
            modelBuilder.Entity("Domain.Models.Address", b =>
                {
                    b.HasOne("Domain.Models.User", "Cust")
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                        .WithMany("Addresses")
                        .HasForeignKey("CustId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__address__cust_id__3A81B327");

                    b.Navigation("Cust");
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.Delivery", b =>
                {
                    b.HasOne("FoodDeliveryProject.Models.DeliveryAgent", "Agent")
=======
            modelBuilder.Entity("Domain.Models.Delivery", b =>
                {
                    b.HasOne("Domain.Models.DeliveryAgent", "Agent")
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                        .WithMany("Deliveries")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__delivery__agent___60A75C0F");

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
                    b.HasOne("FoodDeliveryProject.Models.Order", "Order")
=======
                    b.HasOne("Domain.Models.Order", "Order")
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                        .WithMany("Deliveries")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__delivery__order___5FB337D6");

                    b.Navigation("Agent");

                    b.Navigation("Order");
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.DeliveryAgent", b =>
                {
                    b.HasOne("FoodDeliveryProject.Models.User", "Agent")
                        .WithOne("DeliveryAgent")
                        .HasForeignKey("FoodDeliveryProject.Models.DeliveryAgent", "AgentId")
=======
            modelBuilder.Entity("Domain.Models.DeliveryAgent", b =>
                {
                    b.HasOne("Domain.Models.User", "Agent")
                        .WithOne("DeliveryAgent")
                        .HasForeignKey("Domain.Models.DeliveryAgent", "AgentId")
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                        .IsRequired()
                        .HasConstraintName("FK__delivery___agent__5CD6CB2B");

                    b.Navigation("Agent");
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.FoodItem", b =>
                {
                    b.HasOne("FoodDeliveryProject.Models.Category", "Category")
=======
            modelBuilder.Entity("Domain.Models.FoodItem", b =>
                {
                    b.HasOne("Domain.Models.Category", "Category")
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                        .WithMany("FoodItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__food_item__categ__4316F928");

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
                    b.HasOne("FoodDeliveryProject.Models.Restaurant", "Restaurant")
=======
                    b.HasOne("Domain.Models.Restaurant", "Restaurant")
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                        .WithMany("FoodItems")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__food_item__resta__4222D4EF");

                    b.Navigation("Category");

                    b.Navigation("Restaurant");
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.Order", b =>
                {
                    b.HasOne("FoodDeliveryProject.Models.Restaurant", "Restaurant")
=======
            modelBuilder.Entity("Domain.Models.Order", b =>
                {
                    b.HasOne("Domain.Models.Restaurant", "Restaurant")
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                        .WithMany("Orders")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK__orders__restaura__46E78A0C");

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
                    b.HasOne("FoodDeliveryProject.Models.User", "User")
=======
                    b.HasOne("Domain.Models.User", "User")
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK__orders__user_id__45F365D3");

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.OrderItem", b =>
                {
                    b.HasOne("FoodDeliveryProject.Models.FoodItem", "Item")
=======
            modelBuilder.Entity("Domain.Models.OrderItem", b =>
                {
                    b.HasOne("Domain.Models.FoodItem", "Item")
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__order_ite__item___49C3F6B7");

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
                    b.HasOne("FoodDeliveryProject.Models.Order", "Order")
=======
                    b.HasOne("Domain.Models.Order", "Order")
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__order_ite__order__48CFD27E");

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.Restaurant", b =>
                {
                    b.HasOne("FoodDeliveryProject.Models.User", "User")
                        .WithOne("Restaurant")
                        .HasForeignKey("FoodDeliveryProject.Models.Restaurant", "RestaurantId")
=======
            modelBuilder.Entity("Domain.Models.Restaurant", b =>
                {
                    b.HasOne("Domain.Models.User", "User")
                        .WithOne("Restaurant")
                        .HasForeignKey("Domain.Models.Restaurant", "RestaurantId")
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__restauran__resta__3D5E1FD2");

                    b.Navigation("User");
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.Review", b =>
                {
                    b.HasOne("FoodDeliveryProject.Models.Restaurant", "Restaurant")
=======
            modelBuilder.Entity("Domain.Models.Review", b =>
                {
                    b.HasOne("Domain.Models.Restaurant", "Restaurant")
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                        .WithMany("Reviews")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__review__restaura__5812160E");

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
                    b.HasOne("FoodDeliveryProject.Models.User", "User")
=======
                    b.HasOne("Domain.Models.User", "User")
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__review__user_id__571DF1D5");

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.Category", b =>
=======
            modelBuilder.Entity("Domain.Models.Category", b =>
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                {
                    b.Navigation("FoodItems");
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.DeliveryAgent", b =>
=======
            modelBuilder.Entity("Domain.Models.DeliveryAgent", b =>
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                {
                    b.Navigation("Deliveries");
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.Order", b =>
=======
            modelBuilder.Entity("Domain.Models.Order", b =>
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                {
                    b.Navigation("Deliveries");
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.Restaurant", b =>
=======
            modelBuilder.Entity("Domain.Models.Restaurant", b =>
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                {
                    b.Navigation("FoodItems");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });

<<<<<<< HEAD:FoodDeliveryProject/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("FoodDeliveryProject.Models.User", b =>
=======
            modelBuilder.Entity("Domain.Models.User", b =>
>>>>>>> 82b9a22a46bf5610326f44db57b137d95048852b:Domain/Migrations/AppDbContextModelSnapshot.cs
                {
                    b.Navigation("Addresses");

                    b.Navigation("DeliveryAgent");

                    b.Navigation("Orders");

                    b.Navigation("Restaurant");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
